openshift/cloud-provider-openstack

- cloud-provider-openstack.spec
- images/manila-provisioner/Dockerfile
This is a patch for the upcoming release branch: adds the same Dockerfile and spec file as in 3.11 and rebases to the latest upstream master.
@childsb PTAL
> Add spec and Dockerfile, rebase

- cloud-provider-openstack.spec
Don't use %name for creating the build directory structure.
> Don't rely on %name for build

- cloud-provider-openstack.spec
The %gopath macro is not defined and the previous change breaks the builds.
> Don't use %gopath macro

- docs/using-manila-provisioner.md
- pkg/share/manila/sharebackends/nfs.go
- pkg/share/manila/shareoptions/backend.go
**What this PR does / why we need it**:
This is a fix for Ganesha NFS server who doesn't like the default "0.0.0.0/0" client specifictaion for NFS share. Also adds a requested feature optionally change the NFS client ACL for the export.
Backport of upstream PR https://github.com/kubernetes/cloud-provider-openstack/pull/370
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640639
**Special notes for your reviewer**:
This is a backwards-compatible API change.
```release-note
NONE
```
> Manila: Add StorageClass parameter to specify NFS share client

- images/manila-provisioner/Dockerfile
The OSE 4.0 images don't need to be RPM based and this would simplify the CI/CD process.
> Update Dockerfile to use multi-stage build

- images/manila-csi-plugin/Dockerfile
Updating csi-driver-manila builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/csi-driver-manila.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating csi-driver-manila builder & base images to be consistent with ART

- images/cinder-csi-plugin/Dockerfile
- images/cinder-csi-plugin/Dockerfile.openshift.ci
NodeStage / NodePublish need to call "udevadm trigger".
This is manual cherry-pick of #45
> Bug 1933659: Add udev to the driver image

- pkg/csi/cinder/nodeserver.go
Now we use "findmnt" command to find the device path. Unfortunately, this command may return multiple entries of the same mount, but in fact we need just the first one.
To prevent this issue we add "--first-only" flag to the command.
> Bug 1919291: UPSTREAM: 1434: [cinder-csi-plugin] Fix filesystem resize

- images/cloud-controller-manager/Dockerfile
Affected image: openstack-cloud-controller-manager (occm)
**What this PR does / why we need it**:
imagebuilder used by OSBS/brew to create the product images does not
handle slashes in `COPY` commands well. See e.g.
https://github.com/openshift/imagebuilder/issues/139. This commit
ensures the tree is actually present in the container.
**Special notes for reviewers**:
Brew build with unchanged `COPY` command: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37981954 
Brew build with `COPY . .`: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37983818
```release-note
NONE
```
> Fix ART build

- .ci-operator.yaml
The file named `.ci-operator.yaml` governs which image is used in the
OpenShift CI. This has to be updated as well.
> Bug 1996783: Bump Go to v1.16 - fixup

- go.mod
OpenShift 4.11 is compiled on Go v1.17. A partial revert of https://github.com/openshift/cloud-provider-openstack/pull/114
> go.mod: Revert to Go v1.17

- pkg/openstack/loadbalancer.go
In practice Octavia is quite an unreliable system. We should expect that
load balancers will occasionally go into ERROR state for reasons as
elaborate as race conditions and as simple as lack of resources to spawn
a new Amphora VM.
This commit makes sure that we allow deleting LBs in ERROR state, so
that Services served by such LBs could be deleted and their creation
retried.
Obviously there's room for improvement, as we should probably detect LBs
going into ERROR and attempt to delete and recreate them ourselves, but
this patch is a low hanging fruit fix for the issue.
> Bug OCPBUGS-3827: Allow deleting LBs in ERROR status 

- pkg/openstack/loadbalancer.go
- pkg/util/openstack/loadbalancer.go
`createFullyPopulatedOctaviaLoadBalancer()` ends with a call to
`WaitLoadbalancerActive()`. It'll only exit without error if that
function succeeded. But later on `ensureOctaviaLoadBalancer()` checks
the LB's `ProvisioningStatus` again and exists if it's not ACTIVE. The
problem is that the comparison is done on LB instance returned from POST
call and not from one of the GET calls done in
`WaitLoadbalancerActive()`, so it's always `PENDING_CREATE`. This means
that for LB to be completely created, `ensureOctaviaLoadBalancer()`
always needs to be called twice, increasing number of Octavia calls
made, time for LBs to be created and user experience by creating false
positive warning Event.
In case multiple LBs are created in a short period - `Service.Status`
of the first one will only be …
> Bug OCPBUGS-1646: Make sure LB status is updated immediately

- OWNERS_ALIASES
Adding Jonathan and Roman and Maxim in storage maintainers.
> OCPBUGS-16783: Chore: Update OWNERS_ALIASES

- README.md
- pkg/csi/cinder/controllerserver.go
- pkg/csi/cinder/controllerserver_test.go
- pkg/csi/cinder/openstack/openstack_snapshots.go
- pkg/csi/cinder/openstack/openstack_volumes.go
- tests/playbooks/roles/install-docker/defaults/main.yml
- tests/playbooks/roles/install-docker/tasks/main.yml
Replaces #209 
```
Conflicts:
OWNERS
```
> OCPBUGS-20124: FastFix: Merge https://github.com/kubernetes/cloud-provider-openstack:release-1.25 into release-4.12

- DOWNSTREAM_OWNERS
- DOWNSTREAM_OWNERS_ALIASES
This should allow us to remove the carry and avoid merge conflicts on upstream OWNERS.
> CARRY: Add DOWNSTREAM_OWNERS

- pkg/openstack/loadbalancer.go
- pkg/openstack/openstack.go
- pkg/util/openstack/network.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/results.go
- vendor/modules.txt
Previous code for manage-security-groups were adding the SGs to all the ports attached to the Node. That doesn't make a lot of sense, we only need this traffic opened to the LB members and we only add one port of the Node as the LB member. Moreover we've even tried to add SGs to the ports that had `port_security_enabled=false` which obviously failed.
This patch makes sure that we only add the SG opening NodePort traffic to the port that is actually plugged into the LB. Moreover it adds a check for `port_security_enabled` to make sure that ports with it disabled are ignored.
> OCPBUGS-22974: [release-4.14] manage-security-groups: Only add SGs to LB members (#2455)

- pkg/openstack/events.go
- pkg/openstack/loadbalancer.go
- pkg/openstack/loadbalancer_rename.go
- pkg/openstack/loadbalancer_rename_test.go
- pkg/openstack/loadbalancer_test.go
- pkg/util/openstack/loadbalancer.go
We've deployed clusters configuring CCM with the default `--cluster-name=kubernetes` and this created issues when there are multiple clusters running on a single tenant - if namespace and service names were colliding, there's no way CCM was able to figure out which LB is which and both deployments "stole" LBs from each other.
This commit aims at allowing to change the cluster-name on a running environment and handling all the renames of the LB resources and their tags. A patch updating CCCMO to configure `--cluster-name=<InfrastructureName>` is prepared as well in cluster-cloud-controller-manager-operator#337.
> OCPBUGS-13680: Allow changing cluster-name on existing deployments

- .gitignore
- vendor/github.com/google/gnostic-models/jsonschema/schema.json
- vendor/github.com/google/gnostic-models/openapiv2/openapi-2.0.json
- vendor/go.opentelemetry.io/otel/renovate.json
- vendor/k8s.io/kubernetes/test/e2e/testing-manifests/kubectl/agnhost-primary-service.json
Image build was failing on Konflux due to missing go mod dependencies.
```
2025-04-04 17:27:40,305 ERROR vendor directory changed after vendoring:
A	vendor/github.com/google/gnostic-models/jsonschema/schema.json
A	vendor/github.com/google/gnostic-models/openapiv2/openapi-2.0.json
A	vendor/go.opentelemetry.io/otel/renovate.json
A	vendor/k8s.io/kubernetes/test/e2e/testing-manifests/kubectl/agnhost-primary-service.json
2025-04-04 17:27:42,087 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod. Please check the logs for more details.
```
Konflux ignores .gitignore files since its a possible security gap.
> ART-12521: update go mod dependency for konflux

- pkg/csi/cinder/driver.go
- pkg/csi/cinder/identityserver.go
- pkg/csi/manila/driver.go
- pkg/csi/manila/identityserver.go
This is downstream-first backport of [1] (which is a backport of [2]). The upstream CI is currently broken and I want to get this now while I work on that CI.
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/2872
[2] https://github.com/kubernetes/cloud-provider-openstack/pull/2862
> OCPBUGS-56028: [cinder-csi-plugin] Don't report topology capability when --with-topology=False

- pkg/csi/cinder/driver.go
- pkg/csi/cinder/identityserver.go
- pkg/csi/manila/driver.go
- pkg/csi/manila/identityserver.go
This is downstream-first backport of [1] (which is a backport of [2]). The upstream CI is currently broken and I want to get this now while I work on that CI.
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/2872
[2] https://github.com/kubernetes/cloud-provider-openstack/pull/2862
> OCPBUGS-56027: [cinder-csi-plugin] Don't report topology capability when --with-topology=False
